### PR TITLE
feat: send agent w/autotx

### PR DESCRIPTION
**Pull request by cbrzn**
This PR aims to add the agent with the `send` functionality using [AutoTx](https://github.com/polywrap/AutoTx)

### CODE REVIEW

**Comment by johngriffin** [comment]
Hi, thanks for the PR.  

It looks like this agent signs the swap tx on the back-end rather than passing it to the front end to be signed by the user's wallet in the browser.  Please can you confirm whether this is the case?

**Comment by LachsBagel** [comment]
@cbrzn thanks

@cliffordattractor will leave his comments with regards to integration.

**Comment by cliffordattractor** [comment]
Hi @cbrzn - thanks for the PR.

It looks like this agent signs the swap tx on the back-end rather than passing it to the front end to be signed by the user's wallet in the browser. Please can you confirm whether this is the case?

**Comment by cbrzn** [comment]
> Hi @cbrzn - thanks for the PR.
> 
> It looks like this agent signs the swap tx on the back-end rather than passing it to the front end to be signed by the user's wallet in the browser. Please can you confirm whether this is the case?

hey @cliffordattractor that's not the case, the agents create the transaction object and then returns it so it can be passed to any signer. I [updated the code to show how to get the transaction details](https://github.com/MorpheusAIs/moragents/blob/7953c62a7a4e5ccac65812d90b59c8df1dc28945/submodules/moragents_dockers/agents/src/send_agent/src/agent.py#L46-L53).

I think these transaction objects show be added to the context list which is then passed to the frontend, but not sure - Happy to collaborate with you for front end integration so please let us know any questions or needs you may have :smile:

**Comment by cliffordattractor** [comment]
Hi @cbrzn,

Thanks for clarifying.  In order for us to be able to integrate it we need it to be working end-to-end, so the full user journey should include signing the transaction in the front-end and then the agent providing some feedback regarding the status of the transaction.  

I am currently thinking about how we can make it easier for new agents to integrate with the front-end so I'd be happy to collab with you on that.  As a starting point please check out [how the swap agent currently works](https://github.com/MorpheusAIs/moragents/blob/7953c62a7a4e5ccac65812d90b59c8df1dc28945/submodules/moragents_dockers/agents/src/swap_agent/README.md)

I'd welcome your feedback on the following ideas.  I make these suggestions because I think they will make your job easier to integrate an agent with the front-end, so please let me know if you prefer some alternative.

1.  The chat endpoint should use websockets.  

2. The chat endpoint could return a transaction as well as chat messages, e.g. {'role':'assistant', 'content': '', 'tx':{...}}

3. The front-end should call tx_status as defined in the swap_agent README, but also include the transaction_id, so that the back-end know whether the transaction was initiated or cancelled by the user and can monitor it and then send appropriate messages back to the user via the chat websockets API.

Hope that makes sense, happy to jump on a call to discuss.

**Comment by dOrgJelli** [comment]
Hey @cliffordattractor, thanks for the feedback! Unfortunately we aren't able to dedicate dev time to integrate with the front-end, and when I last talked to Rakshak we were under the impression that this would be done by yourself or someone else working on the app.

I think that you should have everything you need to move forward on getting the transactions generated by autotx and sending those back to the front-end. Please let us know if you have any questions, and also happy to collab on making the front-end integration easy for other agents to use.

**Pull request closed without merging**
