### PR TITLE
add agents/ claim-agent & reward-checking-agent

### PR DESCRIPTION
**Pull request by ygarg25**
I have implemented a reward claim functionality within the swap_agent subfolder. This feature allows users to seamlessly claim their rewards by interacting with a user-friendly interface. The process begins by prompting the user to input the necessary details, including the Pool ID and the Receiver Address. Once these details are provided, the system prepares a claim transaction on behalf of the user.
After preparing the transaction, the interface guides the user through the final steps, prompting them to confirm and execute the transaction to successfully claim their tokens. This streamlined process ensures that users can easily access and retrieve their rewards with minimal effort.

### CODE REVIEW

**Comment by LachsBagel** [comment]
@ygarg25 thanks so much for putting this together to address #48 

I'll be in touch regarding next steps over the coming week.

Thanks

**Comment by ygarg25** [comment]
Hi @LachsBagel, sounds good.
Let me know if you need help with any other feature, would like to contribute further. To discuss the next steps you can contact me on Telegram: @travisbourdain

**Comment by ygarg25** [comment]
@LachsBagel Looking forward to hearing from you whenever you are free

**Comment by LachsBagel** [comment]
@ygarg25 sent you a dm

**Comment by ygarg25** [comment]
claim_agent_1
claim_agent_2
reward_check_1


Hi @Lachsbagel, I have implemented the updated code for integration of both 1) Reward Claiming Agent and 2)GetCurrentUserReward/Reward checking agent
I have implemented this using clifford's router pattern and also added benchmark tests for testing the reward claiming and checking agents. I am attaching these screenshots displaying the interactions between the respective agents and the user and it has integrated successfully into the project. Looking forward to hearing your feedback on this!

**Comment by LachsBagel** [comment]
It looks like the MOR reward and claim agents need information of the user's address and pool ID

From a UX and especially from a safety perspective this behavior should be altered.

The agents should always use the address of the connected wallet.
Your code should directly read and submit that address without needing to pass it through the agent.
Agents should not request or pass along addresses as they can easily malform it.

Moreover, when checking rewards it should go ahead and check both pool 0 and pool 1.
When claiming it should claim from any pool with a non-zero balance.

So the user should just ask:

"how many MOR rewards do I have?"

then your code should pass over the address from the connected wallet.

when they ask

"Claim my MOR rewards"
the claimed tokens should go to the same address, which is read from the browser extension.

**Pull request merged**
